name: Upload Existing Release Assets

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check files
        run: |
          pwd
          ls -lah
          ls -lah release-assets
          test -f release-assets/RKh-CFS-win-v0.1.4.zip
          test -f release-assets/RKh-CFS-Termux-v0.1.4.zip

      - name: Upload ZIP files to v0.1.4
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload v0.1.4 \
            release-assets/RKh-CFS-win-v0.1.4.zip \
            release-assets/RKh-CFS-Termux-v0.1.4.zip \
            --clobber
